version: '3'
services:
  redis:
    image: redis:3.2
    ports:
      - "6400:6379"
  mysql:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    ports:
      - "3310:3306"
